"use client";
import NavBar from "@/components/global/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { useEffect } from "react";
import Footer from "@/components/global/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    // @ts-ignore
    import("preline");
  }, []);
  return (
    <html lang="en">
      <Script src="../../node_modules/preline/dist/preline.js" />
      <body className={inter.className}>
        <div className="relative w-screen min-h-screen overflow-hidden">
          <NavBar />
          <div
            aria-hidden="true"
            className="flex absolute -top-48 left-0 -z-[1]"
          >
            <div className="bg-blue-200 opacity-30 blur-3xl w-[1036px] h-[600px] "></div>
            <div className="bg-slate-200 opacity-90 blur-3xl w-[577px] h-[300px] transform translate-y-32 "></div>
          </div>
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
